---
title: "Organic_carbon"
author: "Joy Buongiorno"
date: '2022-07-29'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load library}
library(ggplot2)
library(scales)
library(dplyr)
```

```{r read in data}
org_chem<-read.csv("/Users/joy.buongiorno/Documents/Research/Svalbard_MAG_analysis/2021_R_Analysis/TOC_outliers_removed.csv")
```

```{r cross plot of C:N vs. d13C}
cols<-c("F" = "#cc79a7","P" = "#5e29c2ff", "AC" = "#0072b2", "AB" = "#39c706ff", "HA" = "#f0e442") # To match colors in mean coverage figure
plot<-ggplot(org_chem, aes(x=CtoN, y=d13C, shape=Station, color=Station, fill = Station)) +
  geom_point(aes(fill=Station), colour="black", size=4, stroke=2) +
  scale_shape_manual(values = c(21, 22, 23, 24, 25)) +
  scale_fill_manual(values=cols) +
  theme_bw(base_size = 30) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  labs(x="C/N", y=expression(paste(delta^{13}, "C (\u2030 vs. PDB)")))
plot
```

```{r summary C/N}
summary_CtoN <- na.omit(org_chem) %>%
  group_by(Station) %>%
  summarize(average = mean(CtoN), max = max(CtoN), min = min(CtoN))
summary_CtoN
```       
```{r summary d13C}
summary_d13C <- na.omit(org_chem) %>%
    group_by(Station) %>%
  summarize(average = mean(d13C), max = max(d13C), min = min(d13C))
summary_d13C
```
